# Generated by Django 3.2.9 on 2021-12-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='https://www.pngfind.com/pngs/m/676-6764065_default-profile-picture-transparent-hd-png-download.png', max_length=500),
        ),
    ]
