# Generated by Django 3.2.9 on 2021-12-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=600)),
                ('quantity', models.IntegerField(default=1)),
                ('images', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('CARS', 'Cars'), ('HOME', 'Home'), ('GARDEN', 'Garden'), ('OTHER', 'Other')], default='OTHER', max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
