# Generated by Django 3.2.9 on 2021-12-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_alter_advert_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='advert',
            name='images',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
